### ISSUE TITLE
Add 🤗 related custom TFX components to the Pipeline

### ISSUE THREAD

**Issue by deep-diver** [deep-diver/semantic-segmentation-ml-pipeline#19]
There are two custom TFX components:
- [`HFModelPusher`](https://github.com/deep-diver/semantic-segmentation-ml-pipeline/tree/main/training_pipeline/pipeline/components/pusher/HFModelPusher): It creates a model repository at 🤗 Model Hub if not exist, then pushes a trained model (from `Trainer`) to the newly created branch in the repository.

- [`HFSpacePusher`](https://github.com/deep-diver/semantic-segmentation-ml-pipeline/tree/main/training_pipeline/pipeline/components/pusher/HFSpacePusher): It creates a space repository at 🤗 Space Hub if not exists, then pushes all the files under the designated directory(this can be set in [`configs.py`](https://github.com/deep-diver/semantic-segmentation-ml-pipeline/blob/1ccc712bd372dee59d91e6969c3ea95051148000/training_pipeline/pipeline/configs.py#L34) to main branch of the repository. 

Usage:
```
# Configs

HF_MODEL_RELEASE_ARGS = {
    "HF_MODEL_RELEASE": {
        "ACCESS_TOKEN": "$HF_ACCESS_TOKEN",
        "USERNAME": "chansung",
        "REPONAME": PIPELINE_NAME,
    }
}

HF_SPACE_RELEASE_ARGS = {
    "HF_SPACE_RELEASE": {
        "ACCESS_TOKEN": "$HF_ACCESS_TOKEN",
        "USERNAME": "chansung",
        "REPONAME": PIPELINE_NAME,
        "APP_PATH": GRADIO_APP_PATH,
        "MODEL_HUB_REPO_PLACEHOLDER": MODEL_HUB_REPO_PLACEHOLDER,
        "MODEL_HUB_URL_PLACEHOLDER": MODEL_HUB_URL_PLACEHOLDER,
        "MODEL_VERSION_PLACEHOLDER": MODEL_VERSION_PLACEHOLDER,
    }
}
```

```python
# Pipeline
trainer = Trainer(...)

pusher_args = {
    "model": trainer.outputs["model"],
}

pusher_args["custom_config"] = hf_model_release_args
hf_model_pusher = HFModelPusher(**pusher_args).with_id("HFModelPusher")
components.append(hf_model_pusher)

space_pusher_args = {
    "model": hf_model_pusher.outputs["pushed_model"],
    "custom_config": hf_space_release_args,
}
hf_space_pusher = HFSpacePusher(**space_pusher_args).with_id("HFSpacePusher")
components.append(hf_space_pusher)
```

Note that the configs are defined in `configs.py`. `$HF_ACCESS_TOKEN` is already set in GitHub Secret, and it will be injected when the action is triggered. All we have to do is add two components in the pipeline as exactly as the usage except replacing `GRADIO_APP_PATH` with the appropriate module path.

**Comment by deep-diver** [comment]
or we can completely re-write those components as proposed in `TFX-Addon`

**Comment by deep-diver** [comment]
I have not tested if custom component works in notebooks yet! Let's try together since I am interested how it goes too :) 

For starter, you can look into [this notebook](https://github.com/deep-diver/semantic-segmentation-ml-pipeline/blob/main/notebooks/tfx_pipeline.ipynb) which uses `InteractiveContext`.

To use custom components, I guess you can clone this repository, and import the appropriate modules.

**Comment by sayakpaul** [comment]
No, I was asking if a single TFX component (even the legacy ones) can be tested in isolation using the InteractiveContext.

**Comment by deep-diver** [comment]
I guess so if possible, but components have dependencies. Like, `HFModelPusher` depends on `Trainer`, and `Trainer` depends on `ImportExampleGen`.

**Comment by deep-diver** [comment]
@sayakpaul 

After #33 is merged, a good starting point would be create a notebook with TFX interactive context. However, since `HFPusher` expects a model as input, you need to create a dummy `Model` artifact as below ([borrowed from tfx official repo](https://github.com/tensorflow/tfx/blob/master/tfx/components/pusher/executor_test.py)):

```python
import standard_artifacts

model = standard_artifacts.Model()
model.uri = os.path.join(<MODEL_PATH_IN_LOCAL_FILESYSTEM>)

# optional
model_blessing = standard_artifacts.ModelBlessing()
model_blessing.set_int_custom_property('blessed', 1) # set 0 to simulate not-blessed situation
```

Then feed those inputs to a `HFPusher`:

```python
hf_pusher = HFPusher(
    username=<YOUR_HF_ACCOUNT>,
    access_token=<YOUR_HF_ACCESS_TOKEN>,
    repo_name=<REPOSITORY_NAME_WHERE_TO_PUSH_IN_HF>,
    model=model,
    model_blessing=model_blessing,
    space_config={
        "app_path": <APP_PATH_IN_LOCAL_FILESYSTEM>
    }
)
```

Also note that you should have SavedModel and Gradio app templates in the `model.uri` and `app_path` respectively within local filesystem.

**Comment by sayakpaul** [comment]
@deep-diver could you point me to the notebook from your recent Vertex AI work that uses the custom HF components?

**Comment by deep-diver** [comment]
@sayakpaul 

sorry for the late reply. I actually didn't build a notebook for HF components, but I could demonstrate with some dummy information (maybe tomorrow). How does that sound?

**Comment by sayakpaul** [comment]
Do you have a script that collates the components together in your recent
Vertex project?

**Comment by deep-diver** [comment]
I don't have unit-test scripts for those, but I can guide some as follows:
1. [run pipeline with HFPusher related arguments](https://github.com/deep-diver/mlops-hf-tf-vision-models/blob/6eda80f27211573ece7ba35266839161d324d3ab/hf_integration/kubeflow_runner.py#L39)
2. [the actual values of the HFPusher related arguments](https://github.com/deep-diver/mlops-hf-tf-vision-models/blob/6eda80f27211573ece7ba35266839161d324d3ab/hf_integration/pipeline/configs.py#L193)
3. [how HFPusher is added in the pipeline](https://github.com/deep-diver/mlops-hf-tf-vision-models/blob/6eda80f27211573ece7ba35266839161d324d3ab/hf_integration/pipeline/kubeflow_pipeline.py#L131)
4. [where the Gradio app is defined](https://github.com/deep-diver/mlops-hf-tf-vision-models/tree/main/hf_integration/app/gradio)

**Comment by sayakpaul** [comment]
Thank you!
