### ISSUE TITLE
Re-generate low-resolution image dataset in TFRecord

### ISSUE THREAD

**Issue by deep-diver** [deep-diver/semantic-segmentation-ml-pipeline#27]
Regenerate low-resolution image datasets in TFRecord. It should follow the same format as the full-resolution datasets:

```python
feature_description = {
    "image": tf.io.VarLenFeature(tf.float32),
    "image_shape": tf.io.VarLenFeature(tf.int64),
    "label": tf.io.VarLenFeature(tf.float32),
    "label_shape": tf.io.VarLenFeature(tf.int64),
}
```

**Comment by sayakpaul** [comment]
Related to #24.

**Comment by deep-diver** [comment]
maybe I will handle this issue to practice how to generate / host TFRecords myself since you have done this many times :) WDYT?

**Comment by sayakpaul** [comment]
Sure thing. Please assign me as a reviewer then.
