### ISSUE TITLE
Swap the dataset

### ISSUE THREAD

**Issue by sayakpaul** [deep-diver/semantic-segmentation-ml-pipeline#35]
We have been able to get the pipeline working. The pipeline can:

* Ingest data
* Generate data stats
* Train a model 
* Deploy to Vertex AI
* Resolve the best model given a set of different models
* Evaluate the trained model 
* Push the [model to HF Hub](https://huggingface.co/chansung/segformer-training-pipeline)
* Host a [Gradio application](https://huggingface.co/spaces/chansung/segformer-training-pipeline) on HF Spaces

All of the above are orchestrated automatically within a TFX pipeline and are run on Vertex AI end to end. 

If you noticed the Space application, it's not great. The results seem spurious. 

Since our [model architecture](https://github.com/deep-diver/semantic-segmentation-ml-pipeline/blob/main/training_pipeline/models/unet.py) is simple, we think it may not be suitable for modelling complex scene understanding. After all, the dataset is pretty high-resolution, and we had to down-size the images to iterate quickly. So, to allow the readers to get good results, we think it's best to demonstrate the project with a dataset that is suitable for the model architecture we're using. 

To achieve this goal, we will swap the dataset with the one used [here](https://www.tensorflow.org/tutorials/images/segmentation). 

Cc: @deep-diver

**Comment by deep-diver** [comment]
@sayakpaul 

I guess this issue can be closed by now?

**Comment by sayakpaul** [comment]
Yes
