### ISSUE TITLE
fix: give appropriate name to CONCRETE_INPUT

### ISSUE THREAD

**Issue by deep-diver** [deep-diver/semantic-segmentation-ml-pipeline#41]
for the serving signature, `CONCRETE_INPUT` remained as `pixel_values`. This is due to the early stage of development of this project. However, `pixel_values` is no longer the name of the `Input` of the model, so it should be modified appropriately.

**Comment by sayakpaul** [comment]
@deep-diver can this be closed?

**Comment by deep-diver** [comment]
I am now checking this issue by giving an appropriate name
